learning_rate = 0.0009178612514712445
model_version = 101
checkpoint = 1
epochs = 100
log_interval = 1
checkpoint_interval = 5
batch_size = 32
batch_sample = 4
train_ratio = 0.8
device = "auto"
weight_decay = 0.05
grad_clip = 1.0