[training]
learning_rate = 2e-4
model_version = 116
checkpoint = 1
epochs = 10
log_interval = 1
checkpoint_interval = 5
batch_size = 32
batch_sample = 4
train_ratio = 0.8
device = "auto"
weight_decay = 1e-2
grad_clip = 3.5
